'use strict';
/*
 * Offline build step: precompute the EV value table V*[mask] for the Генерал
 * ruleset and write it to ../ev-table.js (a shippable global, ~16k numbers).
 *
 * Run:  node tools/build-ev.js
 *
 * Validation (printed): the engine plays its OWN optimal policy against REAL
 * random dice over many games; the realised mean must converge to par = V*[0].
 * Because the dice are real (not the model's distribution), a divergence would
 * expose a bug in the reroll table — a genuine end-to-end check.
 *
 * Note on the ~254.59 figure: that is standard Yahtzee's par (with upper bonus +
 * Yahtzee joker). This ruleset has neither (bare 14-bit mask), so its par is a
 * different, engine-computed number; we do not compare to 254.59.
 */
var fs = require('fs');
var path = require('path');
var General = require('../game.js');
var EV = require('../engine.js');

var t0 = Date.now();
process.stdout.write('Computing V* over ' + (1 << EV.NCAT) + ' states');
var V = EV.computeTable(function (done, total) {
  if ((done % 4096) === 0) process.stdout.write('.');
});
process.stdout.write('\n');
EV.setTable(V);
var par = V[0];
console.log('par (V*[empty]) =', par.toFixed(4), ' in ' + ((Date.now() - t0) / 1000).toFixed(1) + 's');

// ---- Monte-Carlo self-consistency: optimal policy vs real dice ----
function rng() { return Math.random(); }
function rollN(n) { var d = []; for (var i = 0; i < n; i++) d.push(1 + Math.floor(rng() * 6)); return d; }

function playOptimalGame() {
  var scores = {}, total = 0;
  for (var turn = 0; turn < EV.NCAT; turn++) {
    var dice = rollN(5).sort(function (a, b) { return a - b; });
    for (var rl = 2; rl > 0; rl--) {
      var ev = EV.evaluate(scores, dice, rl);
      var keep = ev.best_keep;
      // re-roll the non-kept dice
      dice = dice.map(function (v, i) { return keep[i] ? v : (1 + Math.floor(rng() * 6)); })
                 .sort(function (a, b) { return a - b; });
    }
    var fin = EV.evaluate(scores, dice, 0);
    var cat = fin.best_category.key;
    var got = General.scoreFor(cat, dice);
    scores[cat] = got; total += got;
  }
  return total;
}

var N = 20000, sum = 0, sumsq = 0;
for (var g = 0; g < N; g++) { var s = playOptimalGame(); sum += s; sumsq += s * s; }
var mean = sum / N, variance = sumsq / N - mean * mean, sd = Math.sqrt(variance);
var se = sd / Math.sqrt(N);
console.log('MC optimal-play mean over ' + N + ' games = ' + mean.toFixed(3) +
            '  (±' + (2 * se).toFixed(3) + ' 95% CI, sd=' + sd.toFixed(1) + ')');
var ok = Math.abs(mean - par) < 4 * se + 0.5;
console.log('self-consistency mean≈par: ' + (ok ? 'PASS' : 'FAIL') + '  (|mean-par|=' + Math.abs(mean - par).toFixed(3) + ')');

// ---- write the shippable table ----
var rounded = Array.prototype.map.call(V, function (x) { return Math.round(x * 1000) / 1000; });
var outPath = path.join(__dirname, '..', 'ev-table.js');
var body =
'/* AUTO-GENERATED by tools/build-ev.js — do not edit by hand.\n' +
'   Optimal end-of-game value table V*[mask] for the Генерал ruleset.\n' +
'   par = V*[0] = ' + par.toFixed(4) + ' ; states = ' + rounded.length + ' */\n' +
'(function (root, factory) {\n' +
'  if (typeof module === "object" && module.exports) module.exports = factory();\n' +
'  else root.GeneralEVTable = factory();\n' +
'})(typeof self !== "undefined" ? self : this, function () {\n' +
'  return { ruleset: "general-v1", par: ' + par.toFixed(4) + ', V: [' + rounded.join(',') + '] };\n' +
'});\n';
fs.writeFileSync(outPath, body);
console.log('wrote ' + outPath + ' (' + (body.length / 1024).toFixed(0) + ' KB)');
if (!ok) process.exit(1);
