'use strict';
/*
 * Offline build step: precompute a mask-only optimal-value table V*[mask] for a
 * FREE experimental column (15 categories, deviation number-part scoring + два
 * чифта), reusing engine.js's validated reroll DP via EV.create(shim).
 *
 * Run:  node tools/build-ev-exp.js
 *
 * Scope / honesty: this table values a single FREE column with EXACT deviation
 * scoring and the exact 3-throw reroll DP. It does NOT fold in the −50 number-
 * part penalty (that is path-dependent on the final upper subtotal — tracking it
 * would blow the state space past anything shippable), nor column-0 forced order,
 * nor column-2 reserve rolls. It is the strong, shippable basis for the EV bot
 * and skill/luck analysis; the penalty is applied to realised scores exactly.
 */
var fs = require('fs');
var path = require('path');
var General = require('../game.js');
var EV = require('../engine.js');

// a ruleset shim the engine factory can consume
function expCategory(p, dice) {
  var best = null, bv = -Infinity;
  General.CATEGORIES_EXP.forEach(function (c) {
    if (typeof p.scores[c.key] === 'number') return;
    var v = General.scoreForExp(c.key, dice);
    if (v > bv) { bv = v; best = c.key; }
  });
  return { category: best, value: bv };
}
var shim = {
  DICE_COUNT: General.DICE_COUNT,
  MAX_ROLLS: General.MAX_ROLLS,
  CATEGORIES: General.CATEGORIES_EXP,
  scoreFor: General.scoreForExp,
  aiChooseHolds: General.aiChooseHolds,
  aiChooseCategory: expCategory,
};
var EVX = EV.create(shim);

var t0 = Date.now();
process.stdout.write('Computing experimental V* over ' + (1 << EVX.NCAT) + ' states');
var V = EVX.computeTable(function (done) { if ((done % 4096) === 0) process.stdout.write('.'); });
process.stdout.write('\n');
EVX.setTable(V);
var par = V[0];
console.log('free-column par (V*[empty]) =', par.toFixed(4), ' in ' + ((Date.now() - t0) / 1000).toFixed(1) + 's');

// ---- Monte-Carlo self-consistency: optimal policy vs REAL dice over one column ----
function rng() { return Math.random(); }
function rollN(n) { var d = []; for (var i = 0; i < n; i++) d.push(1 + Math.floor(rng() * 6)); return d; }
function playOptimalColumn() {
  var scores = {}, total = 0;
  for (var turn = 0; turn < EVX.NCAT; turn++) {
    var dice = rollN(5).sort(function (a, b) { return a - b; });
    for (var rl = 2; rl > 0; rl--) {
      var keep = EVX.evaluate(scores, dice, rl).best_keep;
      dice = dice.map(function (v, i) { return keep[i] ? v : (1 + Math.floor(rng() * 6)); }).sort(function (a, b) { return a - b; });
    }
    var cat = EVX.evaluate(scores, dice, 0).best_category.key;
    var got = General.scoreForExp(cat, dice);
    scores[cat] = got; total += got;
  }
  return total;
}
var N = 20000, sum = 0, sumsq = 0;
for (var g = 0; g < N; g++) { var s = playOptimalColumn(); sum += s; sumsq += s * s; }
var mean = sum / N, sd = Math.sqrt(sumsq / N - mean * mean), se = sd / Math.sqrt(N);
console.log('MC optimal-play mean over ' + N + ' columns = ' + mean.toFixed(3) + '  (±' + (2 * se).toFixed(3) + ' 95% CI, sd=' + sd.toFixed(1) + ')');
var ok = Math.abs(mean - par) < 4 * se + 0.5;
console.log('self-consistency mean≈par: ' + (ok ? 'PASS' : 'FAIL') + '  (|mean-par|=' + Math.abs(mean - par).toFixed(3) + ')');

// ---- write the shippable table ----
var rounded = Array.prototype.map.call(V, function (x) { return Math.round(x * 1000) / 1000; });
var outPath = path.join(__dirname, '..', 'public', 'ev-table-exp.js');
var body =
'/* AUTO-GENERATED by tools/build-ev-exp.js — do not edit by hand.\n' +
'   Mask-only optimal value table V*[mask] for a FREE experimental column\n' +
'   (deviation number part + два чифта; the −50 penalty is NOT in the lookahead).\n' +
'   par = V*[0] = ' + par.toFixed(4) + ' ; states = ' + rounded.length + ' */\n' +
'(function (root, factory) {\n' +
'  if (typeof module === "object" && module.exports) module.exports = factory();\n' +
'  else root.GeneralEVTableExp = factory();\n' +
'})(typeof self !== "undefined" ? self : this, function () {\n' +
'  return { ruleset: "experimental-col-v1", par: ' + par.toFixed(4) + ', V: [' + rounded.join(',') + '] };\n' +
'});\n';
fs.writeFileSync(outPath, body);
console.log('wrote ' + outPath + ' (' + (body.length / 1024).toFixed(0) + ' KB)');
if (!ok) process.exit(1);
